export const FLAG_BITS = {
  MUST_SCAN_SUBDIRS: 0x00000001,
  USER_DROPPED: 0x00000002,
  KERNEL_DROPPED: 0x00000004,
  EVENT_IDS_WRAPPED: 0x00000008,
  HISTORY_DONE: 0x00000010,
  ROOT_CHANGED: 0x00000020,
  MOUNT: 0x00000040,
  UNMOUNT: 0x00000080,
  ITEM_CREATED: 0x00000100,
  ITEM_REMOVED: 0x00000200,
  ITEM_INODE_META_MOD: 0x00000400,
  ITEM_RENAMED: 0x00000800,
  ITEM_MODIFIED: 0x00001000,
  ITEM_FINDER_INFO_MOD: 0x00002000,
  ITEM_CHANGE_OWNER: 0x00004000,
  ITEM_XATTR_MOD: 0x00008000,
  ITEM_IS_FILE: 0x00010000,
  ITEM_IS_DIR: 0x00020000,
  ITEM_IS_SYMLINK: 0x00040000,
  OWN_EVENT: 0x00080000,
  ITEM_IS_HARDLINK: 0x00100000,
  ITEM_IS_LAST_HARDLINK: 0x00200000,
  ITEM_CLONED: 0x00400000,
} as const;

type FlagEntry = {
  bit: number;
  label: string;
  raw: string;
  description: string;
};

const ACTION_FLAGS: ReadonlyArray<FlagEntry> = [
  {
    bit: FLAG_BITS.ITEM_CREATED,
    label: 'Created',
    raw: 'ItemCreated',
    description: 'File or directory was created',
  },
  {
    bit: FLAG_BITS.ITEM_REMOVED,
    label: 'Removed',
    raw: 'ItemRemoved',
    description: 'File or directory was removed',
  },
  {
    bit: FLAG_BITS.ITEM_RENAMED,
    label: 'Renamed',
    raw: 'ItemRenamed',
    description: 'Path was renamed or moved',
  },
  {
    bit: FLAG_BITS.ITEM_MODIFIED,
    label: 'Modified',
    raw: 'ItemModified',
    description: 'File contents changed',
  },
  {
    bit: FLAG_BITS.ITEM_CLONED,
    label: 'Cloned',
    raw: 'ItemCloned',
    description: 'Cloned from another file',
  },
  {
    bit: FLAG_BITS.ITEM_INODE_META_MOD,
    label: 'InodeMetaMod',
    raw: 'ItemInodeMetaMod',
    description: 'Inode metadata changed',
  },
  {
    bit: FLAG_BITS.ITEM_FINDER_INFO_MOD,
    label: 'FinderInfoMod',
    raw: 'ItemFinderInfoMod',
    description: 'Finder info changed',
  },
  {
    bit: FLAG_BITS.ITEM_CHANGE_OWNER,
    label: 'ChangeOwner',
    raw: 'ItemChangeOwner',
    description: 'Owner changed',
  },
  {
    bit: FLAG_BITS.ITEM_XATTR_MOD,
    label: 'XattrMod',
    raw: 'ItemXattrMod',
    description: 'Extended attributes changed',
  },
];

const TYPE_FLAG_BITS = [
  FLAG_BITS.ITEM_IS_DIR,
  FLAG_BITS.ITEM_IS_FILE,
  FLAG_BITS.ITEM_IS_SYMLINK,
  FLAG_BITS.ITEM_IS_HARDLINK,
  FLAG_BITS.ITEM_IS_LAST_HARDLINK,
] as const;

const SYSTEM_FLAGS: ReadonlyArray<FlagEntry> = [
  {
    bit: FLAG_BITS.ROOT_CHANGED,
    label: 'RootChanged',
    raw: 'RootChanged',
    description: 'Watched root moved or removed',
  },
  {
    bit: FLAG_BITS.MOUNT,
    label: 'Mount',
    raw: 'Mount',
    description: 'Volume mounted',
  },
  {
    bit: FLAG_BITS.UNMOUNT,
    label: 'Unmount',
    raw: 'Unmount',
    description: 'Volume unmounted',
  },
  {
    bit: FLAG_BITS.MUST_SCAN_SUBDIRS,
    label: 'MustScanSubDirs',
    raw: 'MustScanSubDirs',
    description: 'Client must rescan subtree',
  },
  {
    bit: FLAG_BITS.USER_DROPPED,
    label: 'UserDropped',
    raw: 'UserDropped',
    description: 'User-space dropped events',
  },
  {
    bit: FLAG_BITS.KERNEL_DROPPED,
    label: 'KernelDropped',
    raw: 'KernelDropped',
    description: 'Kernel dropped events',
  },
  {
    bit: FLAG_BITS.EVENT_IDS_WRAPPED,
    label: 'EventIdsWrapped',
    raw: 'EventIdsWrapped',
    description: 'FSEvent IDs wrapped',
  },
  {
    bit: FLAG_BITS.HISTORY_DONE,
    label: 'HistoryDone',
    raw: 'HistoryDone',
    description: 'Historical replay finished',
  },
] as const;

const DISPLAY_FLAGS: ReadonlyArray<FlagEntry> = [
  ...ACTION_FLAGS,
  ...SYSTEM_FLAGS,
  {
    bit: FLAG_BITS.OWN_EVENT,
    label: 'OwnEvent',
    raw: 'OwnEvent',
    description: 'Generated by this process',
  },
];

const TYPE_FLAG_MASK = TYPE_FLAG_BITS.reduce((mask, bit) => mask | bit, 0);
const DISPLAY_FLAG_MASK = DISPLAY_FLAGS.reduce((mask, flag) => mask | flag.bit, 0);
const ALL_FLAG_MASK = DISPLAY_FLAG_MASK | TYPE_FLAG_MASK;

export type EventFlagDescription = {
  labels: string[];
  tooltip: string;
};

const hasFlag = (bits: number, flag: number): boolean => (bits & flag) === flag;

export function describeEventFlags(flagBits?: number | null): EventFlagDescription {
  if (typeof flagBits !== 'number' || !Number.isFinite(flagBits)) {
    return { labels: ['—'], tooltip: 'No event flags' };
  }

  const summarySource =
    ACTION_FLAGS.find((entry) => hasFlag(flagBits, entry.bit)) ??
    SYSTEM_FLAGS.find((entry) => hasFlag(flagBits, entry.bit));

  const orderedEntries: FlagEntry[] = summarySource
    ? [summarySource, ...DISPLAY_FLAGS.filter((entry) => entry !== summarySource)]
    : [...DISPLAY_FLAGS];

  const matchedEntries = orderedEntries.filter((entry) => hasFlag(flagBits, entry.bit));

  const labels = matchedEntries.map((entry) => entry.label);

  if (!labels.length) {
    labels.push('Other');
  }

  const tooltipParts = matchedEntries.map(
    (entry) => `${entry.raw} (0x${entry.bit.toString(16)}): ${entry.description}`,
  );

  const unknownBits = flagBits & ~ALL_FLAG_MASK;
  if (unknownBits) {
    tooltipParts.push(`Unknown: 0x${unknownBits.toString(16)}`);
  }

  const tooltip =
    tooltipParts.length > 0
      ? `${tooltipParts.join('\n')}\n(flags: 0x${flagBits.toString(16)})`
      : `0x${flagBits.toString(16)}`;

  return { labels, tooltip };
}
