import { useCallback } from 'react';
import { useStoredState } from './useStoredState';

const STORAGE_KEY = 'cardinal.ignorePaths';
const DEFAULT_IGNORE_PATHS = [
  '# 0 files in the 2026-02-24 sample. Keep external volumes excluded to avoid indexing large mounted disks/network shares.',
  '/Volumes/',
  '# Cloud provider stubs under CloudStorage may issue network I/O on first traversal (e.g. OneDrive).',
  '~/Library/CloudStorage',
  '',
  '# 2,384,029 files across 414 roots. Node dependency trees dominate index volume and are regenerated.',
  '**/node_modules/',
  '',
  '# 1,178,011 files across 1 root. iOS simulator runtime volumes are huge generated SDK trees.',
  '/Library/Developer/CoreSimulator/Volumes/',
  '',
  '# 807,360 files across 103 roots. Library cache trees are high-churn generated app/system cache data.',
  '**/Library/Caches/',
  '',
  '# 575,477 files across 81 roots. pnpm per-project stores are dependency artifacts, not user-authored files.',
  '**/.pnpm/',
  '',
  '# 777,084 files across 1 root. Bun package cache is high-volume dependency artifact storage.',
  '**/.bun/install/cache/',
  '',
  '# 449,342 files across 29 roots. App partition cache directories are browser/electron app cache payloads.',
  '**/Library/Application Support/*/Partitions/*/Cache/',
  '',
  '# 403,015 files across 1 root. App bundles contain large binary/resource trees with low filename-search value.',
  '/Applications/',
  '',
  '# 326,312 files across 1 root. macOS system frameworks/resources are large and mostly static.',
  '/System/Library/',
  '',
  '# 275,101 files across 1 root. Global pnpm content-addressed store is rebuildable cache data.',
  '**/Library/pnpm/store/',
  '',
  '# 209,526 files across 1 root. Command-line tools/SDK payloads are generated development artifacts.',
  '/Library/Developer/CommandLineTools/',
  '',
  '# 178,753 files across 22 roots. Dot-cache directories are tool-managed caches and usually disposable.',
  '**/.cache/',
  '',
  '# 157,087 files across 155 roots. Browser/Electron code caches are transient compiled cache blobs.',
  '**/Code Cache/',
  '',
  '# 142,017 files across 39 roots. App Support Cache directories hold large runtime cache data.',
  '**/Library/Application Support/*/Cache/',
  '',
  '# 125,968 files across 1 root. Homebrew Cellar contains large versioned dependency trees.',
  '/opt/homebrew/Cellar/',
  '',
  '# 122,893 files across 44 roots. Service worker cache stores are high-churn browser app data.',
  '**/Service Worker/CacheStorage/',
  '',
  '# 91,948 files across 1 root. Xcode DerivedData is disposable build/index output.',
  '**/Library/Developer/Xcode/DerivedData/',
  '',
  '# 83,513 files across 2 roots. Local shared tool data is mostly generated cache/storage.',
  '**/.local/share/',
  '',
  '# 70,040 files across 1 root. npm content cache is package artifact storage.',
  '**/.npm/_cacache/',
  '',
  '# 48,386 files across 39 roots. target directories are compiler/build outputs and should not be indexed.',
  '**/target/',
  '',
  '# 31,886 files across 1 root. Gradle caches are dependency/build artifacts and can be rebuilt.',
  '**/.gradle/caches/',
  '',
  '# 28,765 files across 1 root. Cargo registry is Rust dependency cache.',
  '**/.cargo/registry/',
  '',
  '# 25,015 files across 1 root. Homebrew shared docs/assets add large low-signal trees.',
  '/opt/homebrew/share/',
  '',
  '# 16,390 files across 462 roots. IndexedDB contains app/browser internals with many small files.',
  '**/IndexedDB/',
  '',
  '# 8,739 files across 91 roots. WebStorage is browser state data with low filename-search value.',
  '**/WebStorage/',
  '',
  '# 6,122 files across 10 roots. Next.js build output is generated and frequently replaced.',
  '**/.next/',
  '',
  '# Baseline exclusions re-added from previous defaults to avoid common dev/system noise.',
  '/cores/',
  '/dev/',
  '/private/',
  '/System/Volumes/',
  '/usr/share/',
  '/xarts/',
  '/System/Applications/**/Contents/Resources/',
  '',
  '**/.git/',
  '**/__pycache__/',
  '**/.cocoapods/',
  '**/.opam/',
  '**/Cache/',
  '**/Caches/',
  '**/Index.noindex/',
  '**/TextIndex/',
  '**/io.tailscale.ipn.macos/',
  '**/.stversions/',
  '**/wharf/',
  '**/Xcode.app/',
  '**/.local/fsindex*',
  '**/*.com.google.Chrome',
  '**/*.pyc',
  '**/.dat.nosync*',
  '**/webappsstore.sqlite-wal',
  '**/.DS_Store',
  '',
  '**/com.docker.docker/Data/',
  '**/Firefox/Profiles/**/sessionstore-backups/',
  '**/Firefox/Profiles/**/storage/default/',
  '**/Firefox/Profiles/**/storage/permanent/',
  '**/Google/Chrome*/Cache/',
  '**/Google/Chrome*/leveldb/',
  '**/IconJar*/Backups/',
  '**/Sublime Text */Index/',
  '**/var/postgres/base/',
  '**/var/postgres/pg_stat_tmp/',
  '**/var/postgres/pg_wal/',
  '**/Spotify/Users/*/pending-messages*',
  '',
  '/Library/Biome/',
  '/Library/DuetExpertCenter/',
];

const keepStringEntries = (next: unknown[]): string[] =>
  next.filter((item): item is string => typeof item === 'string');

export function useIgnorePaths() {
  const [ignorePaths, setIgnorePathsState] = useStoredState<string[]>({
    key: STORAGE_KEY,
    defaultValue: DEFAULT_IGNORE_PATHS,
    read: (raw) => {
      const parsed = JSON.parse(raw);
      if (!Array.isArray(parsed)) return null;
      return keepStringEntries(parsed);
    },
    write: (value) => JSON.stringify(value),
    readErrorMessage: 'Unable to read saved ignore paths',
    writeErrorMessage: 'Unable to persist default ignore paths',
  });

  const setIgnorePaths = useCallback(
    (next: string[]) => {
      setIgnorePathsState(next);
    },
    [setIgnorePathsState],
  );

  return { ignorePaths, setIgnorePaths, defaultIgnorePaths: DEFAULT_IGNORE_PATHS };
}
